### ISSUE TITLE
Interoperability tests with Go gossipsub implementation

### ISSUE THREAD

**Issue by Mikerah** [ChainSafe/gossipsub-js#16]
After the other tests are completed, we need to make sure that this JS implementation of gossipsub is interoperable with the Go reference implementation. 

- [ ] Using a libp2p daemon, test whether any peer running either JS or Go implementations of gossipsub can receive and handle each others messages. Based these tests on the [ipfs pubsub interop tests](https://github.com/ipfs/interop/blob/master/test/pubsub.js).

- [ ] Get started on [these interop tests provided by libp2p](https://github.com/libp2p/interop)

**Comment by vasco-santos** [comment]
Hey @Mikerah 

Our interop tests for pubsub currently live in [ipfs/interop/test/pubsub.js](https://github.com/ipfs/interop/blob/master/test/pubsub.js). 

In the meantime, I am working on getting the [libp2p/interop/](https://github.com/libp2p/interop/) repo ready for being used. Expect news on this repo in the next weeks. I am trying to have the time to get this ready before you get into the interop tests for this implementation.

**Comment by Mikerah** [comment]
@vasco-santos Thanks for the heads up. I will be playing with the ipfs pubsub tests that you posted in the upcoming weeks.

**Comment by vasco-santos** [comment]
I created [libp2p/interop#17](https://github.com/libp2p/interop/pull/17) in order to test the interoperability with the go implementation. Things seem to be working at a first glimpse
