### ISSUE TITLE
Licensing for this library

### ISSUE THREAD

**Issue by Mikerah** [ChainSafe/gossipsub-js#2]
Since the eventual goal of this library is to be used within the Libp2p js project, this library should be licensed under the MIT License. All Libp2p repositories are licensed under this license. 

Also, since there is a lot of intersection between the gossipsub protocols and floodsub protocols, it is going to be easier to use open-sourced components in order to build out this library.

**Comment by Mikerah** [comment]
Thoughts @ChainSafe and @GregTheGreek?

**Comment by ChainSafe** [comment]
SGTM!
