### ISSUE TITLE
Go incompatible with JS

### ISSUE THREAD

**Issue by tobowers** [ChainSafe/gossipsub-js#47]
Hi hi,

I noticed that Go cannot publish messages that JS receives when using elliptic keys. That's because Go inlines the public key into the peer ID. We already worked on this issue with just general connections, but it appears it's broken in PubSub additionally.

This PR: https://github.com/libp2p/js-peer-id/pull/101 will allow the issue to be fixed and enable finishing up this TODO: https://github.com/libp2p/js-libp2p-pubsub/blob/master/src/message/sign.js#L76

**Comment by wemeetagain** [comment]
Thanks for the heads up!

**Comment by GregTheGreek** [comment]
@tobowers Let us know if there's anything you could use help with!

We identified a few issues surrounding message signing two weeks ago during the ETH2 interop, but we've been pretty heads down.

**Comment by tobowers** [comment]
Great! Well - making good progress on the inlined keys. What else did you find?
