### ISSUE TITLE
Create an npm module for message cache

### ISSUE THREAD

**Issue by Mikerah** [ChainSafe/gossipsub-js#5]
When the message cache implementation is stable and fully tests (e.g when #3 is complete), it makes sense to refactor it into its own npm module. Several of these data structures that were created for libp2p such as [the time cache](https://www.npmjs.com/package/time-cache) have their own modules and are widely used for different projects.

**Comment by GregTheGreek** [comment]
Is this relevant?

**Comment by Mikerah** [comment]
Maybe not. But, the message cache is it's own data structure just like the time cache is. The time cache is used throughout js-libp2p projects. I'm not sure if the message cache is as extensively used.

**Comment by vasco-santos** [comment]
I would suggest that if we create a new module that needs a message cache, we extract it from here to its own module. Until then, we can close this issue
