### ISSUE TITLE
Expose hooks for message validator before replaying

### ISSUE THREAD

**Issue by mpetrunic** [ChainSafe/gossipsub-js#54]
Currently we can either disable `gossipIncoming` option or gossipUnverified messages.
Proposed solution would be to add hooks (optional param) when subscribing to topics, where we can pass function that decodes message and verifies it. If that hook throws, we ignore and don't gossip that message. 

Proposed alternative
```javascript
gossip.subscribe("topic", (message) => transformedMessage)

gossip.on("topic", (transformedMessage) => {}) 
```

**Comment by wemeetagain** [comment]
I'm thinking of doing something like this in our gossipsub impl in lodestar.
eg:
```typescript
class LodestarGossipSub extends Gossipsub {
  // fancy features
}
```
Pubsub/Gossipsub provides a `validate(message): boolean` that we can/will need to overload that gets called in the right spot.

**Comment by mpetrunic** [comment]
> Pubsub/Gossipsub provides a `validate(message): boolean` that we can/will need to overload that gets called in the right spot.

That was my first idea, but then we would have to decode message twice. First time in validate, second time when event is received.
Other problem is that in validate we don't know the topic and thus we don't know how to decode message.

**Comment by wemeetagain** [comment]
The decoding twice thing is definitely not ideal. We might want to tweak things there.

RE not knowing the topic, the message object that validate receives has a list of topics attached, so we can dispatch to a topic-specific validating function if we have it around.
eg something like:
```typescript
interface Message {
  from?: Buffer;
  data?: Buffer;
  seqno?: Buffer;
  topicIDs: string[];
  signature?: Buffer;
  key?: Buffer;
}
class MyGossip {
  topicValidators: Map<string, (message: Message): boolean>;
  validate(message: Message): boolean {
    return message.topicIDs
      .map(topic => this.topicValidators.get(topic))
      .every(validator=> !validator || validator(message));
  } 
}
```

**Comment by tuyennhv** [comment]
Unstale

**Comment by tuyennhv** [comment]
This issue was done.
