### ISSUE TITLE
Implements spec v1.1 ?

### ISSUE THREAD

**Issue by sbhamad** [ChainSafe/gossipsub-js#68]
Good work!!

Is this implementation of the updated spec? v1.1?

I am not aware of the differences between the two spec versions, but wanted to ask here.

Thanks

**Comment by vasco-santos** [comment]
Hello @sbhamad !

No, this currently implements spec v1.0, you can check the current status of the implementations, as well as the differences on [libp2p/specs/pubsub/gossipsub](https://github.com/libp2p/specs/tree/master/pubsub/gossipsub).
